apiVersion: v1
kind: Secret
metadata:
  name: dbsecret
type: Opaque
data:
  databaseurl: amRiYzpteXNxbDovLzE5Mi4xNjguMS40OjMzMDYvdGVzdD9zZXJ2ZXJUaW1lem9uZT1HTVQlMkI4
  password: MTIzNDU2
  username: cm9vdA==